login: &login
  adapter:  mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: goalara_db
  password: koTGDkg0o,xzWOE7x87F
  socket: '/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock'
  host: localhost


development:
  database: goalara_development
  <<: *login
  
test:
  database: goalara_test
  <<: *login
 
production:
  database: goalara_production
  <<: *login




