login: &login
  adapter:  mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: vI.4XVZb7K8h_tDPl0O&)
  socket:  <%=
    ['/Applications/XAMPP/xamppfiles/sbin/mysqld.sock' #osx-xampp local?
     '/opt/local/var/run/mysql5/mysqld.sock', # darwinports
     '/opt/local/var/run/mysqld/mysqld.sock', # darwinports, again
     '/var/run/mysqld/mysqld.sock',           # ubuntu/debian (linode)
     '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>


development:
  database: goalara_development
  <<: *login
  
test:
  database: goalara_test
 <<: *login
 
production:
  database: goalara_production
  <<: *login




