development:
  database: goalara_development
  adapter:  mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: goalara_db
  password: koTGDkg0o,xzWOE7x87F
  # socket: '/tmp/mysql.sock'
  host: localhost
  
test:
  database: goalara_test
  adapter:  mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: goalara_db
  password: koTGDkg0o,xzWOE7x87F
  # socket: '/tmp/mysql.sock'
  host: localhost
  
 
production:
  database: goalara_production
  adapter:  mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: goalara_db
  password: koTGDkg0o,xzWOE7x87F
  # socket: '/tmp/mysql.sock'
  host: localhost
  




