login: &login
  

development:
  database: goalara_development
  adapter:  mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: admin
  socket: '/tmp/mysql.sock'
  host: localhost
  
test:
  database: goalara_test
  <<: *login
 
production:
  database: goalara_production
  <<: *login




